-- 创建 gm_tasks 任务配置表
CREATE TABLE gm_tasks (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    uuid TEXT NOT NULL DEFAULT '',
    sha256 TEXT NOT NULL DEFAULT '',
    user_id INTEGER NOT NULL DEFAULT 0,
    title TEXT NOT NULL DEFAULT '',
    desc TEXT NOT NULL DEFAULT '',
    type INTEGER NOT NULL DEFAULT 1,
    expression TEXT NOT NULL DEFAULT '',
    method INTEGER NOT NULL DEFAULT 1,
    method_params TEXT NOT NULL DEFAULT '',
    status INTEGER NOT NULL DEFAULT 1,
    error_message TEXT NOT NULL DEFAULT '',
    created_at INTEGER NOT NULL DEFAULT 0,
    updated_at INTEGER NOT NULL DEFAULT 0
);